dist: trusty
sudo: true

addons:
  chrome: stable

install:
  - wget -N http://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - sudo mkdir -p /opt
  - sudo mv -f ~/chromedriver /opt
  - sudo chmod +x /opt/chromedriver

language: scala

scala: 2.12.6

jdk: oraclejdk8

script:
  - make travis

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt
